# Generated by Django 4.2.16 on 2024-10-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_apimetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='id_photo_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
